"""Update to add phone_number to user table

Revision ID: 913a7ebb6468
Revises: 62926e9168a6
Create Date: 2025-01-30 22:52:56.661439

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "913a7ebb6468"
down_revision: Union[str, None] = "62926e9168a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phone_number", sa.String(length=11), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
