"""Add unique ti province table and UniqueConstraint to city

Revision ID: 9267e9952a91
Revises: 913a7ebb6468
Create Date: 2025-01-31 10:17:50.557635

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9267e9952a91"
down_revision: Union[str, None] = "913a7ebb6468"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_name_province_id", "city", ["name", "province_id"])
    op.create_unique_constraint(None, "province", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "province", type_="unique")
    op.drop_constraint("_name_province_id", "city", type_="unique")
    # ### end Alembic commands ###
